LineLength:
  Enabled: false
HashSyntax:
  Enabled: false
Next:
  Enabled: false
IfUnlessModifier:
  Enabled: false
FileName:
  Enabled: false
LeadingCommentSpace:
  Enabled: false
AllCops:
  Exclude:
    - Guardfile
